### ISSUE TITLE
Change property name 'date' to 'value'

### ISSUE THREAD

**Issue by dzhitomirsky-sc** [OpusCapita/react-dates#1]
To be consistent to _react_ component naming convention that supports *onChange* and *value* properties, please change _date_ property name to _value_.

This is not just a cosmetic change - libraries like *redux-form* us react-common notation to inject it's own specific props to declared inputs.

**Comment by kvolkovich-sc** [comment]
Fixed in https://github.com/OpusCapita/react-dates/commit/2f552c982463da09db2d8d2055a03ed27d76936e

**Comment by kvolkovich-sc** [comment]
Released v0.0.1-beta.5

**Comment by dzhitomirsky-sc** [comment]
Done.
