### ISSUE TITLE
'Today' button is not translated

### ISSUE THREAD

**Issue by dzhitomirsky-sc** [OpusCapita/react-dates#10]
Steps to reproduce:
* open react-dates [demp page](https://opuscapita.github.io/react-dates/?currentComponentId=%40opuscapita%2Freact-dates%2F0.1.0%2FDateInput)
* by default, locale of the first date input is _de-DE_
* open datepicker =>  Today button is not translated.

**Comment by kvolkovich-sc** [comment]
See [I18nLinker](https://opuscapita.github.io/react-dates/?currentComponentId=%40opuscapita%2Freact-dates%2F0.1.0%2FI18nLinker&showSidebar=true) component
