### ISSUE TITLE
Add 'nb' locale as fallback for 'no' locale

### ISSUE THREAD

**Issue by mpritchin-sc** [OpusCapita/react-dates#14]
DateInput from react-dates doesn't work under Norsk language ('no' language tag).

```
TypeError: Cannot read property 'firstDayOfWeek' of null
```

MomentJS not supported Norsk['no'] language, but are supported 'nb' & 'nn'. We can add this language but not clear what formats and translations should be.

**Comment by kvolkovich-sc** [comment]
Looks ok.
