### ISSUE TITLE
Date range: impossible to enter value by keyboard

### ISSUE THREAD

**Issue by dshwedovski-sc** [OpusCapita/react-dates#17]
In Invoice application used concept to fillout all fields by keyboard without using mouse.
For this compnent this aproach isn't work.

**Comment by dshwedovski-sc** [comment]
Checked under IE and FF
DateRange Input has posibility to enter date by keyboard

**Comment by kvolkovich-sc** [comment]
Fixed in. https://github.com/OpusCapita/react-dates/pull/18
