### ISSUE TITLE
Add 'onFocus' & 'onBlur' event support

### ISSUE THREAD

**Issue by alevchuk-sc** [OpusCapita/react-dates#2]
As we need to collaborate with other components we might need some more common react-input api event.
For the first touch lets add 'onFocus' & 'onBlur' as the most used ones.

**Comment by kvolkovich-sc** [comment]
Implemented. https://github.com/OpusCapita/react-dates/commit/1ff2e19bb3440375d819726eef7701d277c9e850

**Comment by kvolkovich-sc** [comment]
Please use 0.0.1-beta.7

**Comment by dzhitomirsky-sc** [comment]
Done.
