### ISSUE TITLE
DateInputField doesn't support dates with no leading zero

### ISSUE THREAD

**Issue by skarjalainen** [OpusCapita/react-dates#23]
DateInputField component doesn't support dates that have values without leading zero.

For example in Finland the date format is D.M.YYYY

Date examples:
1.12.2017
31.3.2017

[react-maskedinput](https://github.com/insin/react-maskedinput) must be changed to something else to achieve this kind of masks.

**Comment by kvolkovich-sc** [comment]
@skarjalainen Is it a strict requirement?
I tried to implement it today but the mask ugly jumps. And it not comfortable for user when he input date with keyboard.

**Comment by skarjalainen** [comment]
@kvolkovich-sc Users are used to look at dates without zeroes all around the app and it could be confusing if the zeroes are required when editing the value.

@asergeev-sc This suggestion looks good.

Placeholder: ' D. M.YYYY'
Typing: '31. -.----'

Displaying white space before day/month if the value is below 10.

**Comment by kvolkovich-sc** [comment]
Done.
