### ISSUE TITLE
Show calendar week in date picker

### ISSUE THREAD

**Issue by asergeev-sc** [OpusCapita/react-dates#24]
See how it is done in [bootstrap-datepicker](https://uxsolutions.github.io/bootstrap-datepicker), just click "Calendar weeks" checkbox and open date picker:
![bootstrap-datepicker-as-example](https://user-images.githubusercontent.com/24603787/29568195-4001f118-8758-11e7-889d-c7eff7b99dbd.png)

**Comment by kvolkovich-sc** [comment]
Fixed here https://github.com/OpusCapita/react-dates/commit/1a912cb43d54ee950ed154a07cc95302d46c4db2
