### ISSUE TITLE
Doesn't work with React-0.14.8

### ISSUE THREAD

**Issue by ddivin-sc** [OpusCapita/react-dates#28]
It doesn't work when I try include this module in js-react-attribute

**Comment by kvolkovich-sc** [comment]
Problem: `react-day-picker` started to use `PureComponent`.

Issue with `react@0.14.8` appears after updating `react-day-picker` to lastest version to solve this issue: https://github.com/OpusCapita/react-dates/issues/24

@ddivin-sc try to use `@opuscapita/react-dates@0.3.0-beta.10`
