### ISSUE TITLE
cannot open `DateRangeInput`'s popover

### ISSUE THREAD

**Issue by geminiyellow** [OpusCapita/react-dates#29]
here is my code. `DateRangeInput`'s popover not working, but `DateInput` is ok.

`version: beta13`

```
import React from 'react';
import { DateRangeInput } from '@opuscapita/react-dates';

export default class extends React.PureComponent {
  constructor(options) {
    super(options);

    this.state = { value: [] };
    this.handleChange = this.handleChange.bind(this);
  }

  handleChange(value) {
    this.setState({ value });
  }

  render() {
    return (
      <DateRangeInput
        onChange={value => this.setState({ value })}
        value={this.state.value}
      />
    );
  }
}
```

**Comment by kvolkovich-sc** [comment]
It's strange. Can you provide more details or better source files on github?

**Comment by geminiyellow** [comment]
sorry @kvolkovich-sc that is all my code. 
the `X` and the `▼` is working, but when i click the input, not thing happen here.

**Comment by geminiyellow** [comment]
@kvolkovich-sc ok got it, my fault, i use some css like `div:not { pointer-events: auto; }`.

**Comment by geminiyellow** [comment]
and now , the popover is working, but, 

![image](https://user-images.githubusercontent.com/929878/30585004-6f935c54-9d66-11e7-8ec7-2c70c825b548.png)

`getCoords` has some problem?

**Comment by kvolkovich-sc** [comment]
Should be already in latest versions.
