### ISSUE TITLE
Draw date input calendar with non-form tag

### ISSUE THREAD

**Issue by alevchuk-sc** [OpusCapita/react-dates#3]
As we might want to use _date input_ inside **\<form>\</form>** tag, it is really not a good idea to draw calendar using form, because it can cause problems if embedded forms.

**Comment by kvolkovich-sc** [comment]
Fixed - https://github.com/OpusCapita/react-dates/commit/1fe2685311343dfa09e1b89945cce2bea6c4f203

**Comment by dzhitomirsky-sc** [comment]
Done.
