### ISSUE TITLE
Due to latest change in react-autocompletes@2.0.0, there is some error in react-dates

### ISSUE THREAD

**Issue by lakshgoel95** [OpusCapita/react-dates#30]
ERROR in /var/tmp/base/~/@opuscapita/react-dates/lib/DateVariants/DateVariants.react.js
    Module not found: Error: Can't resolve '@opuscapita/react-autocompletes/lib/VerticalList' in '/var/tmp/base/node_modules/@opuscapita/react-dates/lib/DateVariants'

react-dates also require an update it seems. Can you please look into this

**Comment by kvolkovich-sc** [comment]
Looks strange cause `@opuscapita/react-dates` has fixed version of `@opuscapita/react-autocompletes`.

I just tried use `@opuscapita/react-dates@0.3.0-beta.13` and  `@opuscapita/react-autocompletes@2.0.2` together and everything is OK.

Which version of **npm** do you have?

**Comment by lakshgoel95** [comment]
I am using npm 5.4.0

**Comment by kvolkovich-sc** [comment]
Tried with npm 5.4.0 - everything works. Is there your project code somewhere at github to I can try it?

**Comment by lakshgoel95** [comment]
pull from service einvoice-send, branch: fix5/2
pull form service sales-invoice, branch: fix/2

**Comment by kvolkovich-sc** [comment]
I created codesandbox example where you can ensure that its works ). https://82xpopjwr9.codesandbox.io/

**Comment by lakshgoel95** [comment]
Thanks. I will look into my code what issue it is.
