### ISSUE TITLE
DateInput doesn't position popup properly inside Showroom wrapped component

### ISSUE THREAD

**Issue by estambakio-sc** [OpusCapita/react-dates#31]
**How to reproduce:** visit [this link](https://opuscapita.github.io/react-crudeditor/branches/showroom/) and try to pick a date in any of 2 bottom left DateInput pickers.

**What is expected:** date picker pops up right on top of input field.

**What is actually happening:** popup appears much higher that expected.

Confirmed in Chrome & Firefox.

**Comment by abaliunov-sc** [comment]
Component position is corrected.
Done
