### ISSUE TITLE
Webpack is configured to build library named 'MarkdownInput' which seems to be wrong

### ISSUE THREAD

**Issue by asergeev-sc** [OpusCapita/react-dates#36]
See https://github.com/OpusCapita/react-dates/blob/master/config/webpack.config.js#L73

**Comment by estambakio-sc** [comment]
Closing because it was fixed in https://github.com/OpusCapita/react-dates/pull/54/commits/886ee6fe86fe2f9fbcf42c45b793687e6ef62196.
