### ISSUE TITLE
After onBlur fired clear DateInput in case incorrect date was entered manually

### ISSUE THREAD

**Issue by dzhitomirsky-sc** [OpusCapita/react-dates#4]
Use case:
* User enter invalid date manually
* Focus out of the date input
* invalid user input is left inside the input

TODO:
* in case value is invalid - clear the the input before onBlur is fired

**Comment by kvolkovich-sc** [comment]
Fixed here: https://github.com/OpusCapita/react-dates/commit/57856f4219d0c7caba387127ec7b0d8045657518

Please use `opuscapita-react-dates@0.0.1-beta.10`

**Comment by dzhitomirsky-sc** [comment]
Done.
