### ISSUE TITLE
Click outside of "DayPicker" popup of "DatePicker" doesn't close it

### ISSUE THREAD

**Issue by kvolkovich-sc** [OpusCapita/react-dates#43]

**Comment by abaliunov-sc** [comment]
Done. 
See [https://opuscapita.github.io/react-dates/branches/bug(slash)DatePicker/(hash)43](https://opuscapita.github.io/react-dates/branches/bug(slash)DatePicker/(hash)43)

**Comment by kvolkovich-sc** [comment]
Fixed
