### ISSUE TITLE
It is impossible to choose 1 day only

### ISSUE THREAD

**Issue by amogdalov-sc** [OpusCapita/react-dates#45]
Test steps:
1.1 Enter first date in datepicker and try to select the same date for the end of period.
Actusl result: All dates have been removed from datepicker.

**Comment by abaliunov-sc** [comment]
Done. See [https://opuscapita.github.io/react-dates/branches/issue-45(slash)date-range-one-day/?currentComponentName=DateRangeInput&showSidebar=true](https://opuscapita.github.io/react-dates/branches/issue-45(slash)date-range-one-day/?currentComponentName=DateRangeInput&showSidebar=true)
