### ISSUE TITLE
It is impossible to change only one date in datepicker (start or end of period)

### ISSUE THREAD

**Issue by amogdalov-sc** [OpusCapita/react-dates#47]
Test steps:
1. Select first and second date for period.
2. Click on the first or second date and try to change it
Actual result: First date is always changed and it is necessary to enter period from very begin again. The first and the second date.

**Comment by kvolkovich-sc** [comment]
See detail here: https://github.com/OpusCapita/react-dates/issues/46
I suggest to consider this problem as duplicate, so I close this issue.
