### ISSUE TITLE
Consider usage of "dayjs" instead of "momentjs"

### ISSUE THREAD

**Issue by kvolkovich-sc** [OpusCapita/react-dates#53]
Meta-Info | Value
-- | --
ExtProjectId | JCCMMN-01
Original Estimation | 8h
Remaining Estimation | 0h

https://github.com/xx45/dayjs

**Comment by estambakio-sc** [comment]
[Demo for QA](https://opuscapita.github.io/react-dates/branches/issue-53-dayjs/?currentComponentName=DateInput)

Date input behavior has changed. Please check all relevant cases.

**Comment by nstoliar-sc** [comment]
Tested. Date pickers work correctly. It is possible to change format and language of date pickers. Please, merge with master branch. Spent 1.5 hours.
