### ISSUE TITLE
Add possibility to define disabled days

### ISSUE THREAD

**Issue by asergeev-sc** [OpusCapita/react-dates#55]
Meta-Info | Value
-- | --
ExtProjectId | JCPROC-01
Original Estimation | 10h
Remaining Estimation | 10h

Add the same possibilities as it is available in react-day-picker [disabledDays](http://react-day-picker.js.org/examples/disabled). This possibility should be available in the following components:
- DateInput
- DateRangeInput

**Comment by kvolkovich-sc** [comment]
@nstoliar-sc, please test.

https://opuscapita.github.io/react-dates/branches/issue-55-disabled-days/?currentComponentName=DateInput

Each of `DateInput`, `DatePicker`, `DateRangeInput` components has example with disabled days.
