### ISSUE TITLE
Possibility to pass custom placeholder to DateInput

### ISSUE THREAD

**Issue by hvalkova-sc** [OpusCapita/react-dates#6]
Please add possibility to pass placeholder to DateInput, different from 'date format'.
Example:
 ```
<DateInput
    placeholder={placeholder}
    {...otherProps}
 />
```

**Comment by kvolkovich-sc** [comment]
We discussed your proposal with @asergeev-sc and came to the conclusion that it 	
redundant.

Display input placeholder **dateFormat** as `DD/MM/YYYY` made for better user experience.
