### ISSUE TITLE
Components don't work properly inside modal dialog

### ISSUE THREAD

**Issue by kvolkovich-sc** [OpusCapita/react-dates#64]
Meta-Info | Value
-- | --
ExtProjectId | JCPROC-01
Original Estimation | 1h
Remaining Estimation | 1h
 
![screen shot 2018-11-08 at 8 40 04 pm](https://user-images.githubusercontent.com/24652543/48216924-0e0b7980-e397-11e8-838c-b1ac222f22eb.png)

**Comment by nstoliar-sc** [comment]
Tested. Date Select is displayed correctly while selecting data. Date is selected correctly. Please, merge with master branch.
