### ISSUE TITLE
Incorrect drop down popup from the selected field

### ISSUE THREAD

**Issue by ddivin-sc** [OpusCapita/react-dates#67]
Meta-Info | Value
-- | --
ExtProjectId | JCPROC-01
Original Estimation | 4h
Remaining Estimation | ???h

Test to reproduce:
- Open `React Dates` demo page with max width 100%
- Focused on the date input field and scrolled down. As the result see below picture

![Screenshot from 2019-04-02 09:35:50](https://user-images.githubusercontent.com/24733803/55381160-0194e280-552b-11e9-8e1d-4d76c6b4e37d.png)

Original issue: https://github.com/OpusCapita/minsk-core-externals/issues/292

**Comment by ddivin-sc** [comment]
For QA: you can check it on https://opuscapita.github.io/react-dates/branches/issue-67/index.html?currentComponentName=DateInput

**Comment by ddivin-sc** [comment]
Please, review my changes.

**Comment by ddivin-sc** [comment]
Please, test it.

**Comment by nstoliar-sc** [comment]
Tested. Datepicker is scrolled together with input field. Please, merge with master branch.
