### ISSUE TITLE
DateRangePicker shows dropdown with predefined periods sticked to left side 

### ISSUE THREAD

**Issue by estambakio-sc** [OpusCapita/react-dates#69]
Meta-Info | Value
-- | --
ExtProjectId | JCPIM-01.3
Original Estimation | 10h
Remaining Estimation | 10h

Original issue: https://github.com/OpusCapita/minsk-core-externals/issues/316

## How to reproduce

- visit https://opuscapita.github.io/react-dates//branches/master/index.html?currentComponentName=DateRangeInput&showSidebar=false
- on the bottom (enabled) input click rightmost button with down-facing arrow.

## Expected behavior

Dropdown appears under the button you've just clicked, sticked to the right side of input

## What actually happens

Dropdown appears on the left side instead.

**Comment by estambakio-sc** [comment]
Looks like it was introduces here: https://github.com/OpusCapita/react-dates/commit/44d477e44ddac149f4f07115f233f1154c428db5#diff-fc4226bb02e2fa72464d1dcc1f8f2492R18

**Comment by nstoliar-sc** [comment]
Tested. Dropdown appears under the button which was clicked, sticked to the right side of input. Please, merge with master branch.

**Comment by estambakio-sc** [comment]
Please also test `DateInput` for the same bug (compare to `master`) https://opuscapita.github.io/react-dates/branches/issue-69/index.html?currentComponentName=DateInput&showSidebar=true

**Comment by nstoliar-sc** [comment]
Tested. Datepicker and Dropdown are opened correctly for date input. Please, merge with master branch.
