### ISSUE TITLE
DateInput calendar displayed incorrectly in the bottom and top of screen

### ISSUE THREAD

**Issue by nkovalenko-sc** [OpusCapita/react-dates#74]
Meta-Info | Value
-- | --
ExtProjectId | JCPROC-01
Original Estimation | ???h
Remaining Estimation | ???h

In `DateInput` is located in the bottom of screen and calendar opened then calendar is hidden and scrolling to see the full calendar is impossible.

![image](https://user-images.githubusercontent.com/25153097/87538385-caf1c580-c6a4-11ea-9404-603956237da8.png)

**Comment by dkuzmianok-sc** [comment]
Issue cannot be reproduced. According to @nkovalenko-sc, it is not relevant anymore.
